steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-translator'
      - '--build-arg'
      - 'REACT_APP_GEMINI_API_KEY=${_REACT_APP_GEMINI_API_KEY}'
      - '--build-arg'
      - 'REACT_APP_ENVIRONMENT=production'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-translator']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-translator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-translator'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'

images:
  - 'gcr.io/$PROJECT_ID/ai-translator'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REACT_APP_GEMINI_API_KEY: ''
