steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/smart-translation'
      - '--build-arg'
      - 'REACT_APP_GCP_PROJECT_ID=$PROJECT_ID'
      - '--build-arg'
      - 'REACT_APP_API_URL=${_API_URL}'
      - '--build-arg'
      - 'REACT_APP_ENVIRONMENT=production'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smart-translation']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smart-translation'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smart-translation'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'

images:
  - 'gcr.io/$PROJECT_ID/smart-translation'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _API_URL: 'https://backend-url'