export { MicrophoneIcon } from './MicrophoneIcon';
export { StopIcon } from './StopIcon';
export { SwapIcon } from './SwapIcon';
export { SpinnerIcon } from './SpinnerIcon';
export { PlayIcon } from './PlayIcon';
export { TrashIcon } from './TrashIcon';
export { EyeIcon } from './EyeIcon';
export { XIcon } from './XIcon';
export { DetectIcon } from './DetectIcon';
export { ImageIcon } from './ImageIcon';
export type { IconProps } from './types'; 